brain-score/core

pyproject.toml

otherwise domain libraries cannot access shell scripts such as `test_plugin.sh` (https://app.travis-ci.com/github/brain-score/language/jobs/589505636)

include plugin_management bash files in install

---

brainscore_core/plugin_management/test_plugins.py

Plugins that exempt themselves from any `pytest` testing (e.g. for memory-intensive testing) return with 5 instead of 0. This is a quick fix to prevent builds from failing while a more robust solution is implemented.

Flag Travis build for any plugin with non-zero return code - except 5 (I/O)! - from tests 

---

brainscore_core/plugin_management/conda_score.py

In conjunction with brain-score/language [PR #140](https://github.com/brain-score/language/pull/140), prevents infinite loops invoked during `conda` scoring runs.

Prevent infinite `conda` scoring loops

---

brainscore_core/submission/database.py
tests/test_submission/test_database.py

fixes this:
the new unit test fails with the old code, works with the new.

fix duplicate model creation for resubmission

---

.readthedocs.yml

Adds build.os config key [in compliance with Read the Docs v2.0](https://blog.readthedocs.com/use-build-os-config/).

Add `build.os` to `readthedocs.yml`

---

brainscore_core/plugin_management/parse_plugin_changes.py
tests/test_plugin_management/test_parse_plugin_changes.py

This code fixes a bug where the output printed by `get_scoring_info` is not JSON-serializable. In particular, running a simple command like:
```bash
python -c 'from brainscore_core.plugin_management.parse_plugin_changes import get_scoring_info; get_scoring_info("brainscore_language/models/gpt/__init__.py ", "brainscore_language")'
```
prints:
```python
{'modifies_plugins': True, 'changed_plugins': {'models': ['gpt'], 'benchmarks': [], 'data': [], 'metrics': []}, 'is_automergeable': True, 'run_score': 'True', 'new_models': 'distilgpt2 gpt2 gpt2-medium gpt2-large gpt2-xl gpt-neo-2.7B gpt-neo-1.3B', 'new_benchmarks': ''}
```
This output doesn't follow JSON format, particularly because it uses single quotes `'` instead of double quotes `"`, and because it uses `True` and `False` instead of …

Fixed an I/O bug where 'get_scoring_info' would generate a non-JSON serializable string

---

brainscore_core/plugin_management/conda_score.sh
brainscore_core/submission/endpoints.py
tests/test_submission/test_endpoints.py

This PR is motivated by the need to run individual scoring jobs for each model/benchmark pair on an HPC (e.g. Openmind) instead of running a single job to compute scores for all new models and benchmarks in a submission. We handle this by changing the structure of the scoring endpoint to separate getting the model/benchmark names functionality from the actual scoring (for example, to evaluate `ALL_PUBLIC` without necessarily scoring). As a result, the domain-specific plugin manager now has the flexibility to decide the best method for identifying and scoring the model/benchmark pairs.
This PR implements unit tests that separately test the functionality of both model/benchmark retrieval and scoring using dummy models and benchmarks.

Modified endpoint to separate getting models/benchmarks from scoring

---

brainscore_core/plugin_management/test_plugin.sh

Reduce test log size by not logging output from the `conda` env installation step in `test_plugin.sh`.
May help with Travis errors that appear to be correlated with large logs resulting in marking failed tests as passing. For example, see https://app.travis-ci.com/github/brain-score/brain-score/jobs/615240231

Don't log output from `conda` env installation

---

brainscore_core/plugin_management/test_plugin.sh

This PR updates the `test_plugin.sh` to use the current version of Python when initializing the testing conda environments for each plugin. This accommodates the case where the domain-specific brain-score library uses a specific Python version (e.g. Brain-Score Vision requires Python 3.7, so 3.8 wouldn't work).

Updated test plugin script to use current python version

---

brainscore_core/travis/script.yml

Use built-in variable `TRAVIS_SECURE_ENV_VARS` to assess if private tests can be run (requires access to secrets).

Use built-in variable to evaluate secrets access in Travis

---

brainscore_core/plugin_management/conda_score.sh
brainscore_core/plugin_management/test_plugin.sh

* Install `pip` after activating `conda` environment
* `python` version was fixed to `3.8` when running scoring in a conda environment; now inherited from base.

Update conda environment settings for testing and scoring

---

brainscore_core/submission/database.py

Adds a check to see if the db_secret is ':memory:', which is a new testing feature added in [this PR](https://github.com/brain-score/vision/pull/520). This allows for multiple testing runs to progress without database collisions since each testing run will have a new database file in memory.

Allow for in-memory sqlite endpoint testing

---

brainscore_core/submission/database.py
brainscore_core/submission/database_models.py

Database collisions previously occurred because all test runs shared the same testing schema ('public'). This meant that the testing database would sometimes be cleared while other testing runs were using it. 
This PR addresses this by creating a new schema for each testing run (cooperating w/ [PR #528](https://github.com/brain-score/vision/pull/528)). Between each test method, the schema is cleared, and at the end of the testing run, the schema is dropped.
Fixes [issue #516](https://github.com/brain-score/vision/issues/516) in brainscore vision.

New schema for each testing run

---

brainscore_core/plugin_management/import_plugin.py
brainscore_core/plugin_management/test_plugin.sh
tests/test_plugin_management/test_import_plugin.py
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_requirements_and_setup/__init__.py
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_requirements_and_setup/model.py
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_requirements_and_setup/requirements.txt
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_requirements_and_setup/setup.py
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_requirements_and_setup/test.py
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_setup_only/__init__.py
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_setup_only/model.py
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_setup_only/setup.py
tests/test_plugin_management/test_import_plugin__brainscore_dummy/brainscore_dummy/models/dummy_model_setup_only/test.py

Currently, plugins that require specific Python libraries need to specify them in a `requirements.txt` file. This PR also improves this by adding support for `setup.py` files.
One design choice is that `setup.py` precedes `requirements.txt`.

Added support for setup.py

---

brainscore_core/submission/endpoints.py
tests/test_submission/test_endpoints.py

When users were PRing to brain-score with an email not attached to a brain-score account, uids were not being created and assertion errors were occurring in the Jenkins score_plugins job.
This PR closes issue #82.

brain-score uid creation fix

---

brainscore_core/plugin_management/parse_plugin_changes.py
brainscore_core/submission/database.py
tests/test_submission/test_database.py
tests/test_submission/test_endpoints.py

The `public_benchmark_identifiers` method currently returns all identifiers in the `BenchmarkType` table, which include parent Benchmarks that are not meant to be implemented in the codebase or be added to the benchmark registry. For example, the method would return `average_vision` and `neural_vision` as benchmarks, which are not concrete benchmark instances, leading to failures when trying to score submitted models on them. Therefore, this PR changes the method to return all public identifiers from the `BenchmarkInstance` table and adds a unit test to ensure the intended behavior is captured.

Changed public_benchmark_identifiers to avoid parent benchmarks

---

brainscore_core/plugin_management/test_plugin.sh

The current `test_plugin.sh` script creates a custom conda environment for each testing plugin and uses `conda install pip` to install `pip` in that environment. However, `conda install pip` is not guaranteed to install the most recent version of `pip` and `setuptools`, which occasionally leads to the following issue when installing egg-fragmented packages:
```
Installing collected packages: UNKNOWN
Attempting uninstall: UNKNOWN
Found existing installation: UNKNOWN 0.0.0
Uninstalling UNKNOWN-0.0.0:
Successfully uninstalled UNKNOWN-0.0.0
```
This PR resolves this by making sure to update `pip` and `setuptools` prior to installing the brain-score package[ following this Stack Overflow question](https://stackoverflow.com/questions/53077360/pip-install-issue-with-egg-fragments-that-lead-to-an- …

Added pip upgrade to test_plugin.sh

---

brainscore_core/plugin_management/test_plugin.sh

Addresses bug brought up in [Issue 735](https://github.com/orgs/brain-score/projects/3/views/1?pane=issue&itemId=58408553) in the Vision repo. This will capture the generic plugin tests in XML format so that they can be merged with the non-generic plugin tests at the end of our builds.

Add xml writing for generic plugin tests

---

brainscore_core/plugin_management/parse_plugin_changes.py
brainscore_core/plugin_management/test_plugins.py

Previously, when certain files were altered (such as files within the [model_helpers](https://github.com/brain-score/vision/tree/master/brainscore_vision/model_helpers) directory of brainscore_vision), tests were run on all models present in the brainscore_vision repository. This change should ensure that only the following subset of models are run:
- hmax
- alexnet
- CORnet-S
- resnet-50-robust
- voneresnet-50-non_stochastic
- resnet18-local_aggregation
- grcnn_robust_v1
- custom_model_cv_18_dagger_408
- ViT_L_32_imagenet1k
- mobilenet_v2_1.4_224
- pixels
- cvt_cvt-w24-384-in22k_finetuned-in1k_4
- resnext101_32x8d_wsl
- effnetb1_cutmixpatch_augmix_robust32_avge4e7_manylayers_324x288

test only subset of models when all used to be tested

---

brainscore_core/plugin_management/parse_plugin_changes.py
brainscore_core/plugin_management/test_plugins.py

All models were still being tested instead of subset because a Path and string were being compared.

Fix model subset bug

---

brainscore_core/plugin_management/test_plugin.sh

Previously, a new environment was created for each plugin tested, and pip install was used to bring back all of the project dependencies. This method will instead utilize the already created env and clone it, while pulling from the conda cache.

clone overarching env

---

brainscore_core/plugin_management/test_plugin.sh

Since a new shell script is run, conda current env defaults to base, so the previously made conda env name must be found.

fix for finding env to clone

---

brainscore_core/plugin_management/test_plugin.sh

Will revert if breaking. Cloning the environment was causing problems with pip installed packages. Testing using the same pyproject.toml.

retry new env without clone

---

brainscore_core/plugin_management/test_plugin.sh

Currently version mismatches are occurring when using conda install vs. pip install. Until these errors are fixed, reverting to pip install.

revert conda changes until version errors fixed

---

brainscore_core/plugin_management/test_plugin.sh

Adding retries to this install should minimize our issues with torch install
Moving project pip install to top of script should reduce the likelihood of version mismatch
See vision PR [#893](https://github.com/brain-score/vision/pull/893) for successful test

Changing install inside conda env to have retries

---

brainscore_core/travis/script.yml

Goes with vision [PR #664](https://github.com/brain-score/vision/pull/664).
Travis tests do not yet account for autosubmission PRs that have fallen out of date with the `main`/`master` branch. When the target branch (`main`) is ahead of the incoming submission branch, the changed files in `main` are counted as part of "parse_plugin_changes", and consequently "plugin_only" is ruled `False` which triggers a full test run. This is causing a timeout in the Travis tests. 
This PR is a minimal solution that changes the git diff to compare to where the submission branched off of `main`, thereby only considering the changes directly from the submission. This removes the effect on "plugin_only" rulings and allows plugins to resume testing without running the full repo-wide suite.

Changing comparison to common ancestor commit

---

pyproject.toml

In PR #123 readthedocs is throwing the following error:
```sh
× Can not process file:///home/docs/checkouts/readthedocs.org/user_builds/brain-score-core/checkouts/123 (from -r docs/requirements.txt (line 1))
╰─> This package has an invalid `build-system.requires` key in pyproject.toml.
It contains an invalid requirement: 'setuptools>=65.*'
```
Hoping that changing the syntax from `'setuptools>=65.*'` to `'setuptools>=65'` fixes the issue.

Changing syntax of dependency in pyproject.toml

---

brainscore_core/plugin_management/import_plugin.py

following report from Marin Dujmovic:
> on a couple of different Windwos systems is the error [...] I was running into a couple of weeks ago. I guess for some reason it ends up forcing cp1252 instead of utf8 and it throws up this error whenever a plugin is being loaded (metric, benchmark etc.).

set encoding to utf-8 when opening plugin init files

---

pyproject.toml

Now that brainio is on pypi, the pyproject needs to be updated so that core can also be pushed to PyPi.

Point to PyPi package for brainio

---

brainscore_core/submission/endpoints.py

Update info to now point to AWS Jenkins link, as well as AWS job name

update old jenkins link and job name

---

brainscore_core/plugin_management/test_plugins.py

`resnext101_32x8d_wsl` consistently gives Out of memory errors on plugin helper unit tests.
Performing layer mapping ahead of time for all these models may make this PR unnecessary.
See: https://github.com/brain-score/vision/pull/1213

Remove resnext101_32x8d_wsl from MODEL_SUBSET

---

brainscore_core/submission/endpoints.py

Currently only .yml files are pulled in `endpoints.py`. Expanding to support .yaml exension.

Allow for .yaml extension in metadata endpoint
